# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "newnew"
client_id = "c07a660decf17064c5f1d08cb73c8250"
application_url = "https://shipment-fetish-pine-irs.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://shipment-fetish-pine-irs.trycloudflare.com/auth/callback",
  "https://shipment-fetish-pine-irs.trycloudflare.com/auth/shopify/callback",
  "https://shipment-fetish-pine-irs.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "new-wall-discount-test.myshopify.com"
